---
name: Release - On publish

on:
  release:
    types: [published, created]

jobs:
  build-server:
    uses: ./.github/workflows/_reusable-docker-build.yml
    secrets: inherit
    permissions:
      contents: read
      # Needed to upload container images to ghcr.io
      packages: write
      # Needed for attestation
      id-token: write
      attestations: write
    with:
      image_name: lemoer/authentik
      release: true
      registry_dockerhub: false
      registry_ghcr: true
